name: Deploy to FTP
'on':
  push:
    branches:
      - main
jobs:
  web_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Action checkout
        uses: actions/checkout@v2

      - name: Select node version
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Build
        run: |
          npm i
          npm run build

      - name: Deploy
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: $GITHUB_WORKSPACE/dist/regivaldo
          remoteDir: /httpdocs
          options: "--delete --asci"
